from common.handlers.exception_handler import handle_exception